name: Generate Documentation

on:
  workflow_dispatch:
  push:
    paths:
    - '**.ts'
    branches:
    - master

jobs:
  genDocs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" https://api.github.com/repos/Advanced-Command-Handler/docs/actions/workflows/5566837/dispatches -d "{ \""ref\"": \""master\"" }"

