name: Generate Documentation

on:
  workflow_dispatch:
  push:
    paths:
    - '**.ts'
    branches:
    - master

jobs:
  genDocs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git checkout docs

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm ci

      - name: Format & Lint
        run: |
          npm run prettier
          npm run lint

      - name: Generate Documentation
        run: npm run genDocs

      - name: Commit changes
        run: |
          git pull origin docs -f
          git add docs -f
          git commit -m "Generated documentation."
          git push origin docs -f
