name: Generate Documentation

on:
  workflow_dispatch:
  push:
    paths:
    - '**.ts'
    branches:
    - master

jobs:
  genDocs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm ci

      - name: Format & Lint
        run: |
          npm run prettier
          npm run lint

      - name: Generate Documentation
        run: npm run genDocs
#
#      - name: Commit changes
#        uses: EndBug/add-and-commit@v7
#        with:
#          add: 'docs/** --force'
#          message: Generated docs.

