name: Generate Documentation Release

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  genDocs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" https://api.github.com/repos/Advanced-Command-Handler/docs/actions/workflows/12208437/dispatches -d "{ \""ref\"": \""master\"" }"
